packageExtensions:
  swiper@*:
    peerDependencies:
      'react': '^17.0.1'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220426.hash-a30b37d.cjs
